export enum GAME_EVENTS {
  REQUEST_START = "REQUEST_START",
  START_RESPONSE = "START_RESPONSE",

  REQUEST_PNG_IMAGE = "REQUEST_PNG_IMAGE",
  PNG_IMAGE_RESPONSE = "PNG_IMAGE_RESPONSE",

  REQUEST_JSON_CONTENT = "REQUEST_JSON_CONTENT",
  JSON_CONTENT_RESPONSE = "JSON_CONTENT_RESPONDE",

  REQUEST_SPRITE_CONTENT = "REQUEST_SPRITE_CONTENT",
  SPRITE_CONTENT_RESPONSE = "SPRITE_CONTENT_RESPONSE",

  CHANGE_SCENE = "CHANGE_SCENE",
}

