export enum GAME_EVENTS {
  REQUEST_START = "REQUEST_START",
  START_RESPONSE = "START_RESPONSE",

  REQUEST_FILE = "REQUEST_FILE",
  RESPONSE_FILE = "RESPONSE_FILE",

  REQUEST_SOUND = "REQUEST_SOUND",
  RESPONSE_SOUND = "RESPONSE_SOUND",

  CHANGE_SCENE = "CHANGE_SCENE",

  REQUEST_NEW_GAME = "REQUEST_NEW_GAME",

  REQUEST_LOADING = "REQUEST_LOADING",
  UPDATE_LOADING = "UPDATE_LOADING",

  QUIT_APP = "QUIT_APP",
}
