export enum GAME_EVENTS {
  REQUEST_START = "REQUEST_START",
  START_RESPONSE = "START_RESPONSE",

  REQUEST_FILE = "REQUEST_FILE",
  RESPONSE_FILE = "RESPONSE_FILE",

  CHANGE_SCENE = "CHANGE_SCENE",
}
